### PR TITLE
added ayurvedic books

### PR DESCRIPTION
**Pull request by albinsabu2023**
#10 
## Added ayurvedic books section

changes made

- [x] added book titles
- [x] added book author
-  [x] added book image
-  [x] added book description
-  [x] added book link to book
-  [*] added book section responsive

Screenshot (254)

### CODE REVIEW

**Review by MUDITJAINN — COMMENTED** [review]
Add links to the books provided also only add those books which are freely available to read.

**Comment by albinsabu2023** [comment]
All set . 
- [x] added free books .
- [x] The button explore is the link to corresponding book that can be read free

**Comment by albinsabu2023** [comment]
bro can you just correct the label name as hacktober ,hacktoberfest-accepted .You are missing 'k'

**Comment by MUDITJAINN** [comment]
@albinsabu2023 done

**Pull request merged**
