### PR TITLE
Create resource section

### PR DESCRIPTION
**Pull request by anushree0809**
Used links from government websites, articles and news websites.

### CODE REVIEW

**Comment by anushree0809** [comment]
@MUDITJAINN could you please review this PR? Let me know if any changes are needed to be done!

**Comment by anushree0809** [comment]
Ok will work on this and update!

**Comment by MUDITJAINN** [comment]
Whats the update?

**Comment by anushree0809** [comment]
Yes, updated the PR. Here is how the page looks:
[https://drive.google.com/file/d/1KtzlIS1RzyLdCgeTt_kJ7zV4w-WIAV6C/view?usp=sharing](screen recording of the page)

**Pull request merged**
